{{- if and .Values.decisioningAuthoring.enabled (eq .Values.global.project "tree") }}
{{- $iamUrl := printf "%s" .Values.global.iam.url -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: decisioning-configmap
  namespace: decisioning-service
data:
  HEALTH_TOPIC_NAME: "health-check-topic"
  RESOURCE_NAME: "tree"
{{ end }}